#!/usr/bin/env bash

# ./_results/batch_helper.pl "taskset -c 0 perf stat -e cpu_core/event=0xc4,umask=0x00,name=br_inst_retired.all_branches/,cpu_core/event=0x3c,umask=0x00,name=cycles/,cpu_core/event=0xc7,umask=0x04,name=fp_arith_inst_retired.128b_packed_double/,cpu_core/event=0xc7,umask=0x08,name=fp_arith_inst_retired.128b_packed_single/,cpu_core/event=0xc7,umask=0x10,name=fp_arith_inst_retired.256b_packed_double/,cpu_core/event=0xc7,umask=0x20,name=fp_arith_inst_retired.256b_packed_single/,cpu_core/event=0xc7,umask=0x01,name=fp_arith_inst_retired.scalar_double/,cpu_core/event=0xc7,umask=0x02,name=fp_arith_inst_retired.scalar_single/,cpu_core/event=0xc0,umask=0x00,name=inst_retired.any/,cpu_core/event=0xd0,umask=0x81,name=mem_inst_retired.all_loads/,cpu_core/event=0xd0,umask=0x82,name=mem_inst_retired.all_stores/,cpu_core/event=0xb1,umask=0x10,name=uops_executed.x87/,cpu_core/event=0xc2,umask=0x02,name=uops_retired.retire_slots/"
# cp -r _results inst_results

# ./_results/batch_helper.pl "taskset -c 0 perf stat -e cpu_core/event=0xe6,umask=0x01,name=baclears.any/,cpu_core/event=0xc4,umask=0x11,name=br_inst_retired.conditional/,cpu_core/event=0xc4,umask=0x02,name=br_inst_retired.near_call/,cpu_core/event=0xc4,umask=0x08,name=br_inst_retired.near_return/,cpu_core/event=0xc5,umask=0x00,name=br_misp_retired.all_branches/,cpu_core/event=0xc5,umask=0x11,name=br_misp_retired.conditional/,cpu_core/event=0xc5,umask=0x02,name=br_misp_retired.near_call/,cpu_core/event=0xad,umask=0x80,name=int_misc.clear_resteer_cycles/,cpu_core/event=0xad,umask=0x01,name=int_misc.recovery_cycles/,cpu_core/event=0xc3,umask=0x01,cmask=1,name=machine_clears.count/,cpu_core/event=0xc3,umask=0x02,name=machine_clears.memory_ordering/,cpu_core/event=0xc3,umask=0x04,name=machine_clears.smc/,cpu_core/event=0xb1,umask=0x01,name=uops_executed.thread/,cpu_core/event=0xae,umask=0x01,name=uops_issued.any/"
# cp -r _results speculation_results

# ./_results/batch_helper.pl "taskset -c 0 perf stat -e cpu_core/event=0x61,umask=0x02,name=dsb2mite_switches.penalty_cycles/,cpu_core/event=0x80,umask=0x02,name=icache.misses/,cpu_core/event=0x80,umask=0x03,name=icache_accesses/,cpu_core/event=0x80,umask=0x04,name=icache_data.stalls/,cpu_core/event=0x83,umask=0x04,name=icache_tag.stalls/,cpu_core/event=0x79,umask=0x08,cmask=1,name=idq.dsb_cycles_any/,cpu_core/event=0x79,umask=0x08,name=idq.dsb_uops/,cpu_core/event=0x79,umask=0x04,cmask=1,name=idq.mite_cycles_any/,cpu_core/event=0x79,umask=0x04,name=idq.mite_uops/,cpu_core/event=0x79,umask=0x20,name=idq.ms_uops/,cpu_core/event=0x9c,umask=0x01,name=idq_uops_not_delivered.core/,cpu_core/event=0x9c,umask=0x01,cmask=6,name=idq_uops_not_delivered.cycles_0_uops_deliv.core/,cpu_core/event=0x75,umask=0x01,name=inst.decoded.decoders/,cpu_core/event=0x11,umask=0x20,name=itlb_misses.stlb_hit/,cpu_core/event=0x11,umask=0x0e,name=itlb_misses.walk_completed/,cpu_core/event=0xa8,umask=0x01,name=lsd.uops/"
# cp -r _results front_results

# ./_results/batch_helper.pl "taskset -c 0 perf stat -e cpu_core/event=0x47,umask=0x03,cmask=3,name=cycle_activity.stalls_l1d_miss/,cpu_core/event=0x47,umask=0x05,cmask=5,name=cycle_activity.stalls_l2_miss/,cpu_core/event=0x47,umask=0x09,cmask=9,name=cycle_activity.stalls_l3_miss/,cpu_core/event=0xa3,umask=0x14,cmask=20,name=cycle_activity.stalls_mem_any/,cpu_core/event=0x12,umask=0x0e,name=dtlb_load_misses.walk_completed/,cpu_core/event=0x12,umask=0x20,name=dtlb_misses.stlb_hit/,cpu_core/event=0xa6,umask=0x40,cmask=2,name=exe_activity.bound_on_stores/,cpu_core/event=0x48,umask=0x02,name=l1d_pending_miss.fb_full/,cpu_core/event=0x48,umask=0x01,name=l1d_pending_miss.pending/,cpu_core/event=0xd0,umask=0x11,name=mem_inst_retired.stlb_miss_loads/,cpu_core/event=0xd1,umask=0x40,name=mem_load_retired.fb_hit/,cpu_core/event=0xd1,umask=0x01,name=mem_load_retired.l1_hit/,cpu_core/event=0xd1,umask=0x08,name=mem_load_retired.l1_miss/,cpu_core/event=0xd1,umask=0x10,name=mem_load_retired.l2_miss/,cpu_core/event=0xd1,umask=0x20,name=mem_load_retired.l3_miss/,cpu_core/event=0xa2,umask=0x01,name=resource_stalls.any/"
# cp -r _results back_results


# sudo ./_results/batch_helper.pl "taskset -c 0 perf stat -e power/energy-cores/,power/energy-pkg/"

tar -czvf perf.tar.bz2 _results/
scp ./perf.tar.bz2 root@10.154.131.18:~/.